on:
   milestone:
    types: [closed]

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
    - uses: mougenko/create-release-note@v1.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
